spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gestion-tickets
        username: root
        password: root123456
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
        defer-datasource-initialization: true
    thymeleaf:
        cache: false
logging:
    level:
        org:
            springframework:
                security: DEBUG
