spring:
    datasource:
        url: ${DB_URL}
        username: ${USERNAME}
        password: ${PASSWORD}
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
    thymeleaf:
        cache: false
logging:
    level:
        org:
            springframework:
                security: DEBUG
